services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: foodbook_backend
    volumes:
      - ./src:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - db
    networks:
      - foodbook_backend


  nginx:
    image: nginx:latest
    container_name: foodbook_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - foodbook_backend

  db:
    image: mysql:8.0
    container_name: foodbook_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foodbook_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306" # host port -> container port
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - foodbook_backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: foodbook_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 100M
    depends_on:
      - db
    networks:
      - foodbook_backend

networks:
  foodbook_backend:

volumes:
  dbdata: